jeffreysilver/stopcovid-lambdas

.gitignore
dialog.py
drills.py
requirements.txt
simulator.py

Here's a dialog handler that (mostly) works with the sample dialog. It's driven by a command-line simulator instead of by a kinesis stream. (so it should be easy to see where the stream should plug in). I haven't rigorously unit tested because I wanted to make sure the behavior was right first. There are some oddities that I'll ask about in slack.

initial dialog handler with simulator

---

dialog/dialog.py
dialog/test_dialog.py
dialog/test_persistence.py
dialog/types.py
drills-v1.json
drills/drill_content/drills.json
drills/drill_content/translations.json
drills/drills.py
drills/localize.py
drills/test_drills.py
drills/test_localize.py
requirements.txt
simulator.py

Turned out that it was a lot easier to localize downstream from the agent (the simulator in this code, the SMS sender in real life).

localization of drills

---

dialog/dialog.py
dialog/registration.py
dialog/test_dialog.py
dialog/test_registration.py
dialog/types.py
drills/localize.py
drills/test_localize.py
requirements.txt
serverless.yml
simulator.py

Also hacks the simulator to be able to run any of the 7 drills.

validate registration codes the right way

---

__tests__/stopcovid/dialog/test_dialog.py
stopcovid/dialog/dialog.py
stopcovid/dialog/registration.py
stopcovid/dialog/types.py
stopcovid/drills/drills.py
stopcovid/drills/localize.py

Found and fixed a few important bugs in the process.
The tests are a little hard to read, but the idea is that
* given a state
* ..and a comamnd
* ...validate that the resulting events and state make sense

unit testing of dialog agent

---

.github/workflows/black.yml
__tests__/stopcovid/test_event_distributor.py
black.toml
serverless.yml

locally we should run black --config black.toml

move black configuration to black.toml

---

__tests__/stopcovid/dialog/test_dialog.py
__tests__/stopcovid/drills/test_drills.py
__tests__/stopcovid/test_event_distributor.py

should be a minor improvement in clarity

separate answer localization testing from the core of the dialog agent testing

---

__tests__/stopcovid/event_distributor/test_event_distributor.py
__tests__/stopcovid/event_distributor/test_outbound_sms.py
stopcovid/clients/sqs.py
stopcovid/event_distributor/outbound_sms.py

Next up: clean up send message lambda and add sleep logic

Include delay seconds in message attributes for outbound sms

---

stopcovid/event_distributor/event_distributor.py
stopcovid/event_distributor/initiation.py

it's easy and low-risk to do this from the distributor. Once we start on-demand initiation, it'll make sense to move it into its own component.

initiate the first drill

---

__tests__/stopcovid/clients/test_sqs.py
__tests__/stopcovid/event_distributor/test_event_distributor.py
__tests__/stopcovid/event_distributor/test_outbound_sms.py
sample_events/distribute_event.json
stopcovid/clients/sqs.py
stopcovid/event_distributor/outbound_sms.py

The send message lambda will receive an array of messages and will be in charge of sleeping for some amount of time between sending each one to twilio. Note that we arent including the `with_initial_pause` argument from the simulator. Im going to do some heavy testing to see if its needed with the way messages are getting bundled.

Group outbound messages by phone number and send in batch to queue

---

stopcovid/drills/drill_content/translations.json

This just adds translations for correct_response that were missing in previous file.

Adds missing correct_response translations

---

__tests__/stopcovid/status/test_drill_instances.py
stopcovid/status/drill_instances.py
stopcovid/status/users.py

improves isolation and makes our queries simpler

remove reminder_sent from user, add phone number to drill instance

---

__tests__/stopcovid/dialog/test_persistence.py
__tests__/stopcovid/status/test_drill_instances.py
__tests__/stopcovid/status/test_users.py
stopcovid/dialog/dialog.py
stopcovid/dialog/types.py
stopcovid/status/drill_instances.py
stopcovid/status/lambda.py
stopcovid/status/status.py
stopcovid/status/users.py

* Storing sequence number on batches (requires obliteration of events in dynamoDB)
* Propagating that sequence number to drill instances and user progress

idempotence of status context

---

__tests__/stopcovid/dialog/models/test_events.py
__tests__/stopcovid/dialog/test_engine.py
__tests__/stopcovid/integration_tests/test_command_stream.py
sample_events/start_drill_command.json
serverless.yml
simulator.py
stopcovid/command_stream/command_stream.py
stopcovid/dialog/engine.py
stopcovid/status/initiation.py

That makes it a little easier to retry if the drill is malformed.

Change the StartDrill command to use a slug rather than a drill object

---

aws_lambdas/schedule_next_drills_to_trigger.py

to get more than that we'll need to write our own thing

sqs supports a max of 15 minutes of delay

---

aws_lambdas/handle_inbound_sms.py
aws_lambdas/twilio_webhook.py
serverless.yml

Please review carefully given all the nonsense with From/To.
Can't go live in prod until we have idempotence figured out.

webhook for twilio (no more twilio functions)

---

stopcovid/registration.py

Seems like this is all that's required, but I'm not set up to locally test this yet.

Passing intercom_id through from reg form

---

package-lock.json
package.json
serverless.yml

Stop sending logs to serverless, and instead send them to datadog

---

__tests__/stopcovid/status/test_drill_progress.py
manage.py
stopcovid/status/drill_progress.py

* get rid of clear-seq command. This is almost certainly the wrong thing to do now that we have fixed the sharding bug.
* make rebuild-drill-progress a full rebuild by deleting the user first

improvements to reset script

---

__tests__/stopcovid/clients/test_sqs.py
__tests__/stopcovid/send_sms/test_enqueue_outbound_sms.py
aws_lambdas/enqueue_sms_batch.py
serverless.yml
stopcovid/clients/sqs.py
stopcovid/send_sms/enqueue_outbound_sms.py

as previously discussed, we'd like to see the event distributor within the send_sms context. So I made that change. And I added a line of logging that would be helpful for debugging.

move event distributor under send_sms context and add logging

---

__tests__/stopcovid/integration_tests/test_command_stream.py
aws_lambdas/enqueue_sms_batch.py
aws_lambdas/handle_command.py
aws_lambdas/log_message.py
aws_lambdas/schedule_next_drills_to_trigger.py
aws_lambdas/send_sms_batch.py
aws_lambdas/trigger_reminders.py
aws_lambdas/trigger_scheduled_drill.py
aws_lambdas/twilio_webhook.py
aws_lambdas/update_drill_status.py
stopcovid/status/drill_progress.py
stopcovid/utils/verify_deploy_stage.py

Ensures that the stage matches the environment. If it doesn't everything will error out so that we don't corrupt data.
Requires that we each insert a DEPLOY_STAGE=dev and DEPLOY_STAGE=prod key into our .env files.

verify that environment matches stage

---

__tests__/stopcovid/drill_progress/test_initiation.py
manage.py
stopcovid/drill_progress/aws_lambdas/trigger_scheduled_drill.py
stopcovid/drill_progress/drill_progress.py
stopcovid/drill_progress/initiation.py

also includes a management command to help us view the problematic stream entry

don't enqueue START_DRILL commands when we're out of drills to start

---

__tests__/stopcovid/dialog/test_engine.py
stopcovid/dialog/engine.py
stopcovid/dialog/registration.py

* Send the stage with the validation API to enable whitelisting phone numbers in dev
* Don't send drill reminders or drill initiations to users who aren't validated

harden validation

---

__tests__/stopcovid/dialog/command_stream/test_publish.py
stopcovid/dialog/command_stream/publish.py
stopcovid/sms/aws_lambdas/twilio_webhook.py

This is an intermediate step towards having a second command stream consumer upd
ate the message log.

stick the twilio webhook payload into the dialog command stream

---

stopcovid/sms/aws_lambdas/twilio_webhook.py

don't double write to the command stream and the message log

---

serverless.yml
stopcovid/drills/drills.py

try to unblock deploy by setting the right s3 permissions

---

stopcovid/drills/content_loader.py
stopcovid/drills/drills.py
stopcovid/drills/localize.py

This PR is just a code reorganization that will make hot reloading easier.

content hot reload phase 1: extract ContentLoader

---

__tests__/stopcovid/drill_progress/test_drill_progress.py
__tests__/stopcovid/drill_progress/test_initiation.py
__tests__/stopcovid/drills/test_drills.py
stopcovid/drill_progress/drill_progress.py
stopcovid/drill_progress/initiation.py
stopcovid/drills/content_loader.py
stopcovid/drills/drills.py

depends on #161. Will rebase after it's in.

get drill slugs from drills context instead of hard coding
